### ISSUE TITLE
Keyboard doesn't work in RustDesk

### ISSUE THREAD

**Issue by kuche1** [sspanak/tt9#552] opened 2024-06-25 19:48 UTC
Perhaps it requires the same input mode as Termux, that is to say, select the character in the tt9 menu, and only then send it to the app.

Rustdesk app is com.carriez.flutter_hbb (https://f-droid.org/en/packages/com.carriez.flutter_hbb/)

**Comment by kuche1** [comment] 2024-06-25 20:28
Update: I actually got the app to build and when I used the proposed code it didn't fix rustdesk and I broke termux

**Comment by sspanak** [comment] 2024-07-01 16:11
Thanks for reporting! To be honest, it's the first time I hear about this application, so I can't tell if it has the same problem as Termux. 

I am currently focused on completing other features, but I can take a look at RustDesk after that.

**Comment by maverick74** [comment] 2024-07-03 09:29
To put some weight on the RustDesk balance plate: **i use RustDesk too** (just not on the phone yet)

I've been using it since almost it's inception and it's just now becoming more widely known. It's a great "TeamViewer" alternative that is Free, OpenSource and CrossPlatform that works pretty well!

**Comment by sspanak** [comment] 2024-07-04 10:03
RustDesk is a good example of why the on-screen keypad still has the "BETA" label. There were several separate problems. I fixed most of them as part of #240. And it needed a bit more tweaking to prevent disappearing punctuation, caused by unnecessary keyboard restarts (fixed in #565).

All in all, RustDesk should work correctly in the next TT9 version.

**Closed** 2024-07-05 05:38 UTC
Labels: bug, app hack
