### ISSUE TITLE
Add a new word - Sonim XP3

### ISSUE THREAD

**Issue by drol845** [sspanak/tt9#456] opened 2024-03-10 19:16 UTC
I am unable to add new words to the dictionary on my Sonim XP3 (XP3800). When I try to do so, I receive an error message that says, _"Cannot add a word when no language is selected"_

I am wondering if I am missing anything or is this a bug on this device?

**Comment by sspanak** [comment] 2024-03-11 17:31
I don't think it is a problem with the device.

I have a couple of questions:

1. Before adding the word, there is a confirmation dialog saying: `Add word "XXX" to "LANGUAGE X"?`. Do you see the name of the language there?
2. Which language are you using? If using many, does it happen with all of them?
3. Has it started happening after you did something specific?

**Comment by drol845** [comment] 2024-03-11 22:02
1. When I press "*" while the cursor is inside the word, I do not receive a confirmation dialog. Instead, I get the pop-up message that says, _"Cannot add a word when no language is selected."_
2. I am using both English and Hebrew languages, and the issue persists in both.
3. It has never worked for me,
4. and it happens with any word, regardless of whether it exists or not.

**Comment by sspanak** [comment] 2024-03-12 17:43
I reviewed the code quickly today, but I can't see anything wrong with it. And I can't reproduce it on any of my phones. I'll take a closer look after completing v29.0.

**Comment by drol845** [comment] 2024-03-18 21:42
Ok I'll try

**Comment by sspanak** [comment] 2024-04-16 07:07
@drol845, are you still experiencing the problem? I was able to test on Sonim XP3 and adding words works without a sign of a problem. 

The new v30.0 is out, by the way, so you can try that too.

**Comment by drol845** [comment] 2024-04-16 16:14
Thank you! I will have to check on it later.

**Comment by drol845** [comment] 2024-05-02 20:26
I installed v31.0 and everything works excellent. Thanks.

**Comment by sspanak** [comment] 2024-05-03 11:19
Perfect. I am closing the issue in this case.

**Closed by sspanak** 2024-05-03 11:19 UTC
Labels: question
