### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#385] opened 2023-10-28 22:30 UTC
I'm experiencing occasional crashes!
But it does not happen very often! They are actually somewhat rare.

They tend to happen when I focus some field. When the crash happens it usually happens 3 or 4 times one after the other for everytime I try to focus the field!!!

(sorry if I could not find a reason or a way to replicate yet...)

**Comment by sspanak** [comment] 2023-11-01 08:02
This may be related to #364. Unfortunately, I will not be able to investigate it anytime soon. In the meantime, could you please collect the logs when a crash occurs? First, go to Settings, then scroll down to the "About" section and tap on the version number. Then enable "Detailed Debug Logs". Use your phone a while until TT9 crashes again. Try making it crash several times in a row, if possible. After that, come back to the developer screen and check the logs. If you see "no logs", enable the system logs. Once they appear, you can tap on the text to copy it and then you can paste it here. I'll try to find out what is wrong when I have free time again.

Have in mind enabling the debug logs may make your phone a bit laggy. Make sure to disable it after copying the logs.

**Comment by maverick74** [comment] 2023-11-03 21:22
I'll try to catch it and post it here!

Thanks for the instructions!

**Comment by maverick74** [comment] 2023-11-15 20:45
Here we go!

TT9 LOG:


11-15 20:24:05.083  3523  3523 D tt9/KeyPadHandler: ===> Start Up; packageName: org.mozilla.firefox inputType: 0 fieldId: -1 fieldName: null privateImeOptions: null imeOptions: 1 extras: null

11-15 20:30:18.877  8381  8381 D tt9/KeyPadHandler: ===> Start Up; packageName: app.varlorg.unote inputType: 131073 fieldId: 2130968578 fieldName: null privateImeOptions: null imeOptions: 1140850691 extras: null

11-15 20:30:22.289  8381  8381 D tt9/onBackspace: backspace handled

11-15 20:30:28.560  8381  8381 D tt9/KeyPadHandler: ===> Start Up; packageName: app.varlorg.unote inputType: 0 fieldId: 2130968595 fieldName: null privateImeOptions: null imeOptions: 0 extras: null

11-15 20:30:32.690  8381  8381 D tt9/KeyPadHandler: ===> Start Up; packageName: com.android.systemui inputType: 0 fieldId: -1 fieldName: null privateImeOptions: null imeOptions: 0 extras: null

11-15 20:30:34.068  8381  8381 D tt9/KeyPadHandler: ===> Start Up; packageName: org.mozilla.firefox inputType: 0 fieldId: -1 fieldName: null privateImeOptions: null imeOptions: 0 extras: null

11-15 20:30:36.130  8381  8381 D tt9/KeyPadHandler: ===> Start Up; packageName: org.mozilla.firefox inputType: 294913 fieldId: -1 fieldName: null privateImeOptions: null imeOptions: 301989890 extras: null

11-15 20:30:40.990  8381  8381 D tt9/KeyPadHandler: ===> Start Up; packageName: io.github.sspanak.tt9 inputType: 0 fieldId: 2131230858 fieldName: null privateImeOptions: null imeOptions: 0 extras: null

11-15 20:30:41.866  8381  8991 D tt9/db.normalizeWordFrequencies: Normalized 0 words in: 1157 ms

-------
ANDROID LOG:

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean p0.a.p()' on a null object reference
	at io.github.sspanak.tt9.ime.TraditionalT9.w(Unknown Source:2)
	at io.github.sspanak.tt9.ime.a.onEvaluateInputViewShown(Unknown Source:10)
	at io.github.sspanak.tt9.ime.TraditionalT9.onEvaluateInputViewShown(Unknown Source:0)
	at android.inputmethodservice.InputMethodService.onShowInputRequested(InputMethodService.java:1672)
	at android.inputmethodservice.InputMethodService.dispatchOnShowInputRequested(InputMethodService.java:1709)
	at android.inputmethodservice.InputMethodService.-wrap0(Unknown Source:0)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:482)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:196)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by sspanak** [comment] 2023-12-09 09:52
@maverick74, sorry for the delayed response. I've been quite busy with personal stuff lately.

The problem is exactly the same as the one mentioned in #364. It will be fixed in the next release.

**Closed** 2023-12-21 12:37 UTC
Labels: bug, duplicate
