### ISSUE TITLE
Main View not Showing when desired

### ISSUE THREAD

**Issue by alexknop** [sspanak/tt9#308] opened 2023-07-20 03:50 UTC
I am using a Sonim XP5s and have noticed that sometimes the main view (black bar on the bottom with suggestions, gear icon, OK icon, etc) does not show in the messaging app when typing.
I did some debugging and noticed that when I can type (and I am sure it's using tt9 due to some of its t9 functions such as creating a "tree") but I can't see the black bar on the screen, onStartInputView isn't called, although onStartInput is. When the main view does show, onStartInputView is called. So I was beginning to see the relevance of the function and it resulting in the main view showing. However it seems these functions are being called by proprietary Android code.
Is there a way to force onStartInputView/main view showing or is that more controlled by the messaging app? I am starting to think it could only be handled by the messaging app or the phone's software instead.
Similarly, if I press the back button when typing a text message, which hides the main view, the keyboard doesn't come back. I have to back out of the conversation and then enter the conversation again.

**Comment by alexknop** [comment] 2023-07-20 04:10
Still poking around... looks like this was attempted in TraditionalT9.Java with forceShowWindowIfHidden() ?

**Comment by sspanak** [comment] 2023-07-20 11:15
`onStartInputView()` and `onStartInput()` are called by each application to tell the keyboard it needs to perform some startup procedure, such as displaying itself. Unfortunately, from my tests, it seems that applications are very inconsistent in calling these two functions. Some call the first one, some call the second and others call both. For this reason, I created `forceShowWindowIfHidden()` in attempt to patch the problem, but sometimes even that function fails.

It's all working fine if you touch a text field, because this is how Android was designed to work in the first place, I guess. But the mechanism fails with a hardware keypad. 

Either way, when the Main View is hidden, you could try simulating a touch event using the OK key. And if that fails too, you need to keep poking the startup functions and `forceShowWindowIfHidden()` and find a way of displaying the UI.

I tried really hard to make this work, even examined the InputMethodService source code in the Android repo, but to no avail. I have no idea how to make it work in all applications... :slightly_frowning_face:

**Comment by alexknop** [comment] 2023-07-20 16:26
I have got this to work on my phone, see pull request #310

**Comment by sspanak** [comment] 2023-07-24 11:41
Right! Just check if the last version I suggested works for you and we can merge it (the one with the correct `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P)`). Github diplayed it somewhat incorrectly the first time, so I pasted the entire function to clear all confusion.

**Comment by sspanak** [comment] 2023-07-26 13:18
The fix is now merged in `master`

**Closed by sspanak** 2023-07-26 13:18 UTC
Labels: bug
