### ISSUE TITLE
Punctuation list - can't go backwards

### ISSUE THREAD

**Issue by asherGe** [sspanak/tt9#679] opened 2024-12-08 18:15 UTC
Hi, I just updated from v31.0 to v41.0 on Sonim XP3900. Lots of new features! Thanks. I especially like the text editing cut/past options!

When I press 1 to get punctuation, I used to use the <- back arrow key to quickly access ? and ! characters. Now pressing the <- back arrow key escapes out of the punctuation list. Is this intentional? I noticed you have a setup option to re-order the punctuation character list. I just changed the order to put the ? and the ! following the , and . characters, which is an acceptable work around.

**Comment by asherGe** [comment] 2024-12-08 18:32
So, this issue is not confined to the punctuation list, it occurs in all the suggestions lists. The back arrow escapes out of the suggestions list rather than selecting the previous (to the left) suggestion.

**Comment by sspanak** [comment] 2024-12-08 20:56
Could you please check the hotkey assignments? Is "Previous Suggestion" assigned to the correct key? If it is not too much trouble for you, could you also try to reset the hotkeys to the defaults? This should definitely fix the problem, if it is caused by a misconfiguration.

Another problem might be some application tampering with the key presses. Does it happen in all apps or only in a specific one?

**Comment by asherGe** [comment] 2024-12-08 22:22
Thanks, yes the "previous suggestion" was assigned to volume up key, apparently by mistake of myself as I was exploring the setup options. I checked my wife's identical phone that I updated at the same time and it had the correct default. Restoring defaults reset it to the correct <- key and works as expected now. Thanks!

**Closed** 2024-12-09 09:01 UTC
Labels: more info needed
