### ISSUE TITLE
Number keys are typed twice in dialer on KYF33

### ISSUE THREAD

**Issue by mcfrei** [sspanak/tt9#261] opened 2023-05-19 21:38 UTC
Thanks so much for keeping the project active and working on it!

Short description: pressing digits in com.android.dialer results with digits being inserted twice often, after a couple of presses.

Device: Kyocera Torque X01 KYF33
Android version: 5.1.1
No touchscreen.

When debugging the issue on my device, I uncommented debug logs and determined that it happens when onStart in TraditionalT9.java is being called twice exactly in the same time, here's the extempt from logcat:
```

2023-05-20 20:29:39.222  4321-4321  onKeyDown               io.github.sspanak.tt9                D  Key: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_1, scanCode=2, metaState=0, flags=0x8, repeatCount=0, eventTime=6183000, downTime=6183000, deviceId=23, source=0x301 } repeat?: 0 long-time: false
2023-05-20 20:29:39.312  4321-4321  onKeyUp                 io.github.sspanak.tt9                D  Key: 8 repeat?: 0
2023-05-20 20:29:39.342  4321-4321  tt9/onStartInput        io.github.sspanak.tt9                D  inputType: 3 fieldId: 2131624130 fieldName: null packageName: com.android.dialer restarting: true
2023-05-20 20:29:39.342  4321-4321  tt9/onStart             io.github.sspanak.tt9                D  Started with input android.view.inputmethod.EditorInfo@18a9c748 isActive: true
2023-05-20 20:29:39.402  4321-4321  tt9/onStartInput        io.github.sspanak.tt9                D  inputType: 3 fieldId: 2131624130 fieldName: null packageName: com.android.dialer restarting: true
2023-05-20 20:29:39.402  4321-4321  tt9/onStart             io.github.sspanak.tt9                D  Started with input android.view.inputmethod.EditorInfo@24b1f9e1 isActive: true
```

I'll try to debug the issue further and update this later.

**Comment by mcfrei** [comment] 2023-05-19 21:41
Here are additional logs, where I pressed [1] then [2] then [3] keys, and got the output 1233 in dialer (key 3 was inserted twice)

Note that I have added additional variables to output when tried to understand what's going on.

```
2023-05-20 20:39:39.272 11367-11367 tt9/onFinishInput       io.github.sspanak.tt9                D  When is this called?
2023-05-20 20:39:39.272 11367-11367 tt9/onStartInput        io.github.sspanak.tt9                D  inputType: 3 fieldId: 2131624130 fieldName: null packageName: com.android.dialer restarting: false
2023-05-20 20:39:39.272 11367-11367 tt9/onStart             io.github.sspanak.tt9                D  Started with input android.view.inputmethod.EditorInfo@24b1f9e1 isActive: false isRestarting: false currentInputConnection: com.android.internal.view.InputConnectionWrapper@3ef02306
2023-05-20 20:39:42.442 11367-11367 onKeyDown               io.github.sspanak.tt9                D  Key: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_2, scanCode=3, metaState=0, flags=0x8, repeatCount=0, eventTime=6786220, downTime=6786220, deviceId=23, source=0x301 } repeat?: 0 long-time: false
2023-05-20 20:39:42.592 11367-11367 onKeyUp                 io.github.sspanak.tt9                D  Key: 9 repeat?: 0
2023-05-20 20:39:42.602 11367-11367 tt9/onStartInput        io.github.sspanak.tt9                D  inputType: 3 fieldId: 2131624130 fieldName: null packageName: com.android.dialer restarting: true
2023-05-20 20:39:42.602 11367-11367 tt9/onStart             io.github.sspanak.tt9                D  Started with input android.view.inputmethod.EditorInfo@138eedc7 isActive: true isRestarting: true currentInputConnection: com.android.internal.view.InputConnectionWrapper@f380ff4
2023-05-20 20:39:48.472 11367-11367 onKeyDown               io.github.sspanak.tt9                D  Key: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_3, scanCode=4, metaState=0, flags=0x8, repeatCount=0, eventTime=6792250, downTime=6792250, deviceId=23, source=0x301 } repeat?: 0 long-time: false
2023-05-20 20:39:48.622 11367-11367 onKeyUp                 io.github.sspanak.tt9                D  Key: 10 repeat?: 0
2023-05-20 20:39:48.632 11367-11367 tt9/onStartInput        io.github.sspanak.tt9                D  inputType: 3 fieldId: 2131624130 fieldName: null packageName: com.android.dialer restarting: true
2023-05-20 20:39:48.632 11367-11367 tt9/onStart             io.github.sspanak.tt9                D  Started with input android.view.inputmethod.EditorInfo@1a73531d isActive: true isRestarting: true currentInputConnection: com.android.internal.view.InputConnectionWrapper@bdb6992
2023-05-20 20:39:48.672 11367-11367 tt9/onStartInput        io.github.sspanak.tt9                D  inputType: 3 fieldId: 2131624130 fieldName: null packageName: com.android.dialer restarting: true
2023-05-20 20:39:48.672 11367-11367 tt9/onStart             io.github.sspanak.tt9                D  Started with input android.view.inputmethod.EditorInfo@1f829f63 isActive: true isRestarting: true currentInputConnection: com.android.internal.view.InputConnectionWrapper@20c03760
```

**Comment by mcfrei** [comment] 2023-05-19 21:53
One other thing I have noticed is that if I try to enter a + sign on the dialer by holding [*] key, If I hold it long enough so the dialer is opened from the main screen, when I release the [*] key I get a * after the +, resulting in the +* sequence in the dialer field. That does not happen if I release the [*] key before the dialer interface is opened (but still hold it long enough to produce the + in the dialer field).

**Comment by sspanak** [comment] 2023-05-20 09:38
I am confused. In #241, you said no numbers appear in 123 mode, but now you say they appear twice. Is #241 still valid?

Anyway, I am not willing to work on a device-specific problem at the moment, but I have a couple of suggestions for debugging. And I would be glad to merge a fix, if you get to the bottom of this problem.

Now, as for key presses being repeated, I remember I had to fix a similar problem in: `preferences/items/ItemClickable.java`, where OK would double click, even though it was pressed once. 

Let's start with checking whether it's the Kyocera or TT9 not working properly. Could you please try out [k9t9](https://github.com/danielshorten/k9t9) or the old Traditional T9 (either from Play Store or try building it from tag `v5.0-last-of-origin`). If they type numbers properly, then TT9 is misbehaving.

Regardless of the above, you could continue the investigation in the current code base. Here are a couple of suggestions:
1. Go to `TraditionalT9.onStart()`. At the end add `if (mInputMode.isDialer()) { onStop(); }`. This will disable TT9 altogether in dialer fields. There are customized on all phones, so it may be a better idea to let Android handle them. However, this may cause problems when typing phone numbers in the Contacts app or in a browser.
2. Change `KeyPadHandler.onKeyUp()` and `KeyPadHandler.onKeyDown()` to return `false` instead of `super.onKeyUp(keyCode, event)` or `super.onKeyDown(keyCode, event)`. This will not trigger the system key event handler, which may be responsible for typing the second number.
3. Try bypassing `ModeDialer.onNumber()` and/or `onOtherKey()`, by just returning `false`. This is another method of letting the system handle the keypress.

**Comment by mcfrei** [comment] 2023-05-20 12:58
Sorry about the confusion, I did not mean to do that.
The issues are about two different fields, this one is about inputting digits in com.android.dialer, and #241 is about inputting digits in "phone number fields" in com.android.contacts, this is the key difference I think.

I perfectly understand that you do not want to work on a device-specific problem and I would gladly try to get to the bottom of the issue myself, in fact, I did quite a lot of changing in the code already for experiments, but I will certainly revert everything and focus the fix commit on the problem if I manage to unravel it.

Regarding k9t9 - I have installed the latest release from github:
https://github.com/danielshorten/k9t9/releases/tag/0.12.0
and I can confirm that it does not duplicate number keys in dialer interface.

Not important: However I am not able to enter a `+` sign using it (just mentioning it, and it's probably because for some reason Kyocera insists that `+` is on a long press of `*` key by showing the tip in the dialer interface)

Regarding the investigation of the code base, I have two questions: 

a) Is variable mInputMode supposed to be assigned twice in TraditionalT9.initTyping? once in the determineAllowedInputModes and second time immediately after?

b) Is there any way where KeyPadHandler.onStartInput can be called twice in a row? Because that is what I am getting whenever the number key is doubled. The parameters are the same, except the difference in InputConnectionWrapper id (after the `@` in toString)

Regarding your suggestions:

1. If I disable TT9 in dialer fields by adding `if (mInputMode.isDialer()) { onStop(); return; }` the `com.android.dialer` input works perfectly, no keys are being typed twice and the `+` symbol is inserted correctly on long press of `*`. However, you are right and the input in phone fields in `com.android.contacts` does not work at all, worsening the state of #241 

2. If I change `KeyPadHandler.onKeyUp()`, `KeyPadHandler.onKeyLongPress()` and `KeyPadHandler.onKeyDown()` to return `false` instead of `super.onKeyXXX(keyCode, event)` the key doubling is still present, and I see calling `onStartInput` twice when that happens, here's the logcat for key being entered once:
```
2023-05-20 11:03:28.964  9829-9829  tt9/onStartInput        io.github.sspanak.tt9                D  inputType: 3 fieldId: 2131624130 fieldName: null packageName: com.android.dialer restarting: true
2023-05-20 11:03:28.964  9829-9829  tt9/onStart             io.github.sspanak.tt9                D  Started with input android.view.inputmethod.EditorInfo@173f7121 isActive: true isRestarting: true currentInputConnection: com.android.internal.view.InputConnectionWrapper@1b016946
2023-05-20 11:03:32.184  9829-9829  onKeyDown               io.github.sspanak.tt9                D  Key: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_2, scanCode=3, metaState=0, flags=0x8, repeatCount=0, eventTime=4103560, downTime=4103560, deviceId=23, source=0x301 } repeat?: 0 long-time: false
2023-05-20 11:03:32.274  9829-9829  onKeyUp                 io.github.sspanak.tt9                D  Key: 9 repeat?: 0
```
and here's the logcat for key being entered twice:
```
2023-05-20 11:03:32.284  9829-9829  tt9/onStartInput        io.github.sspanak.tt9                D  inputType: 3 fieldId: 2131624130 fieldName: null packageName: com.android.dialer restarting: true
2023-05-20 11:03:32.284  9829-9829  tt9/onStart             io.github.sspanak.tt9                D  Started with input android.view.inputmethod.EditorInfo@1fd15707 isActive: true isRestarting: true currentInputConnection: com.android.internal.view.InputConnectionWrapper@2b106034
2023-05-20 11:03:32.324  9829-9829  tt9/onStartInput        io.github.sspanak.tt9                D  inputType: 3 fieldId: 2131624130 fieldName: null packageName: com.android.dialer restarting: true
2023-05-20 11:03:32.324  9829-9829  tt9/onStart             io.github.sspanak.tt9                D  Started with input android.view.inputmethod.EditorInfo@2f80fe5d isActive: true isRestarting: true currentInputConnection: com.android.internal.view.InputConnectionWrapper@205ad3d2
2023-05-20 11:03:34.924  9829-9829  onKeyDown               io.github.sspanak.tt9                D  Key: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_3, scanCode=4, metaState=0, flags=0x8, repeatCount=0, eventTime=4106300, downTime=4106300, deviceId=23, source=0x301 } repeat?: 0 long-time: false
2023-05-20 11:03:34.984  9829-9829  onKeyUp                 io.github.sspanak.tt9                D  Key: 10 repeat?: 0
```

3. If I only return `false` in `ModeDialer.onNumber()` and `onOtherKey()` the keys are not being doubled in dialer interface, however if I enter the dialing interface by long pressing the `*` key for `+`, the `+` is added to the start of the number, but consequent button presses do not produce digits.

**Comment by mcfrei** [comment] 2023-05-20 13:19
Regarding input lifecycle - here's a great answer of [Bernd Kampl](https://stackoverflow.com/users/970998/bernd-kampl) to the question "When is this called?", and probably an answer to key doubling too:
https://stackoverflow.com/a/66238856

**Comment by mcfrei** [comment] 2023-05-20 20:03
Steps to reproduce the current issue is as follows:
Install the keyboard app, all settings by default.
Press [1] on the main phone screen, opens the calling interface with the digit 1 typed.
[2]: 12
[3]: 123
[*]: 123*
[1]: 123*11 (note that the every key after the star is entered twice)
[2]: 123*1122
[3]: 123*112233
Press `[📞/Power]` button to close the calling interface and return to the main phone screen, the steps now can be repeated. Not only `*` button does the duplication of the entered keys, but also `Back button` (key 4 scancode 355) deletes one digit but leads to the following digits double input.

However this behavior is much more erratic in the branch version (221cc21) and I really want to diagnose the issue with doubling keys myself.

**Comment by sspanak** [comment] 2023-05-25 07:55
> The issues are about two different fields, this one is about inputting digits in com.android.dialer, and https://github.com/sspanak/tt9/issues/241 is about inputting digits in "phone number fields" in com.android.contacts, this is the key difference I think.

Got it!

> Regarding k9t9 - I have installed the latest release from github:
https://github.com/danielshorten/k9t9/releases/tag/0.12.0
and I can confirm that it does not duplicate number keys in dialer interface.

Alright, then there is something wrong with the numeric modes in TT9. It's good to know this.

> Is variable mInputMode supposed to be assigned twice in TraditionalT9.initTyping? once in the determineAllowedInputModes and second time immediately after?

That code there probably needs to be cleaned up. I have refactored the initialization too many times and it has become messy. 

`determineAllowedInputModes()` loads the mode and does some validation, then `InputModeValidator.validateMode()` does more validation and returns the actual valid `modeId`. So, yes, both are required at the moment.

> Is there any way where KeyPadHandler.onStartInput can be called twice in a row? Because that is what I am getting whenever the number key is doubled. The parameters are the same, except the difference in InputConnectionWrapper id (after the @ in toString)

From the top of my head: 
a) if the app crashes, it will be restarted, which is something you have fixed in #262, right?

b) `com.android.dialer` tries to take over the control on all phones, so it may be interfering with TT9 somehow. I have had problems with double-action backspace on my phone (see: `TraditionalT9.onBackspace()`). However, I have no problem with any other key. I haven't research how the dialer app works, so I am not sure what is the right choice. We may want to disable key handling completely, or we may want to do it on specific phones.

I am thinking, crashing is either the main culprit or it makes it difficult to debug another simpler problem.

> "When is this called?"

This was written some 10 years ago, before I stepped in the project. :smile:

**Comment by mcfrei** [comment] 2023-05-25 21:50
> Alright, then there is something wrong with the numeric modes in TT9. It's good to know this.

In the version of the code I'm using currently I managed to fix this issue completely by adding this to `ModeDialer.onNumber`:
```
	@Override
	public boolean onNumber(int number, boolean hold, int repeat) {
		 super.onNumber(number, hold, repeat);
		 return false;
	}
```
But I also added this to `KeyPadHandler.onStartInputView`
```
		currentInputConnection = getCurrentInputConnection();
```
and I have a number of other small modifications that could be the culprit.

> That code there probably needs to be cleaned up. <...>  So, yes, both are required at the moment.

Aha, I understand. I have already experimented with it and indeed, changing the initialization does stop keyboard from functioning correctly in other applications. No worries, it is fine. If I find any specific issue to address, I'll create an issue and work on it.

>  We may want to disable key handling completely, or we may want to do it on specific phones.

Could be an option indeed. I noted how I have fixed problem for it earlier, but I have not yet understood how the options menu works and I'm not even sure if that should go in the options menu or not. 

By the way, speaking of backspace, the `back` key as `backspace` function does not correctly consume the pressing of the key in any mode and any application other than the dialer, and instead of deleting the last character, it applies the "go back" android command, effectively closing the application in most cases. Do you think that deserves opening another issue, too? I'm not affected because I use other key as my `backspace` key (thank you so much for putting it in the options!), but `back` as `backspace` is a default functionality on this model so it could be important.

> I am thinking, crashing is either the main culprit or it makes it difficult to debug another simpler problem.

The crashing has been resolved by the fix and I have not seen it happen again.

> This was written some 10 years ago, before I stepped in the project. 😄

Ahaha, sorry about that 😅😅😅

**Comment by sspanak** [comment] 2023-05-26 07:46
> The crashing has been resolved by the fix and I have not seen it happen again. (And yes, I tested your suggested change and it works)

I think it is a good idea to add: `currentInputConnection = getCurrentInputConnection();` to `KeyPadHandler.onStartInputView()` too. Now I remember, I've noticed some apps call only `onStartInputView()`, but not `onStartInput()`, while some call both, when navigating around their interface. You made me realize I missed resetting the `inputConnection`. I'll add it to your PR.

> TL:DR: I have a fix, but not sure how and if I add it to options.

This is indeed strange. What you did in `ModeDialer.onNumber()` is the same as just returning false without doing anything else, because when you do so, the keyCode generated by the parent class never gets processed. In other words, returning false let's the system process the key press. So... are you completely sure this:
```java
	@Override
	public boolean onNumber(int number, boolean hold, int repeat) {
		 super.onNumber(number, hold, repeat);
		 return false;
	}
```
works differently than this:
```java
	@Override
	public boolean onNumber(int number, boolean hold, int repeat) {
		 return false;
	}
```
?

Also, in regards to #264, you could again try returning false in `ModeDialer.onOtherKey()` an it will cause fallback to the system handler.

All in all, I am fine with disabling all custom key handling when `ModeDialer` is on, provided that we don't break anything on other phones. Initially, I wanted to enforce Nokia-like key behavior, but now I see this may not be such a good idea. And I don't mean meddling with the settings, don't worry about them. :slightly_smiling_face: 

> By the way, speaking of backspace...

Unfortunately, it is not possible to have full control over "Back" key. It's because Android allows all applications to process the key press before the IME, if they want to. See [the manual](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#backspace-key-default-press---back). It may be possible to hack around it, but I am not that experienced with Android and I don't know how... :slightly_smiling_face:

**Comment by felipecrs** [comment] 2023-05-27 19:42
Just to say that I'm facing the exact same issue after upgrading to v21 on a LG X100S. Downgrading to v20 solves the problem.

It took me a while to figure this out. 😅

**Comment by sspanak** [comment] 2023-05-29 07:47
I see. Unfortunately, my phone works differently, so I cannot propose the right way of fixing it. 

Could someone try starting with the current `master` and only overriding `onNumber()` and `onOtherKey()` in `ModeDialer`, so that they only return false, without doing anything else? I think this is the way to go, but I have no way of confirming it. :slightly_frowning_face:

**Comment by sspanak** [comment] 2023-05-31 07:55
@felipecrs, @mcfrei, I think of come up with a solution. Please try version 21.8 [from here](https://github.com/sspanak/tt9/releases/tag/v1.0-inital). If not anything else, at least the numeric modes code is simpler now.

**Comment by felipecrs** [comment] 2023-05-31 11:31
Hey @sspanak, that's awesome! But I won't be able to test it for the next 5 days... I'm traveling ATM. Sorry!

**Comment by mcfrei** [comment] 2023-06-02 18:15
I was able to test the latest master 4405c0e (debug) on KYF33 and unfortunately the issue with "typing keys twice in dialer" is present in that version of code.

Additionally after some more testing, it seems that in this version the typing keys twice in dialer issue starts when any key (either numeric or symbol) is hold long enough to produce output without letting go of the key, and it is not limited to number keys, `*` and `#` can also be typed twice. Also, sometimes it randomly stops during typing a long number, here are some examples of dialer output during consecutive key presses, each time reloading the dialer app, each key pressed once, with slightly varied timings, but never long enough to produce input without releasing the key:
`123456789*0##`
`12233445566778899*00##`
`123456778899**00##`
`12344566778899*00##`

There is no specific difference in logcat on these cases, but each button press produces these two lines, and when the keys appear twice, these two lines are repeated almost in the same time consequtively:
```
tt9/validateMode        io.github.sspanak.tt9                W  Invalid input mode: 0 Enforcing: 4
tt9/validateTextCase    io.github.sspanak.tt9                W  Invalid text case: 1 Enforcing: 2
```

**Comment by mcfrei** [comment] 2023-06-02 18:36
Also, unfortunately, if I change ModeDialer.onOtherKey to this in the 4405c0e version (and refactor other relevant classes to add the hold variable to base and all overrides), I can not get the wanted functionality anymore (and I could do it in b3fde40a ):
```
	@Override
	public boolean onOtherKey(int key, boolean hold) {
		if(key == KeyEvent.KEYCODE_STAR && hold){
			keyCode = KeyEvent.KEYCODE_PLUS;
			return true;
		}
		if(key == KeyEvent.KEYCODE_POUND && hold){
			keyCode = KeyEvent.KEYCODE_SEMICOLON;
			return true;
		}
		return false;
		//return !Key.isDecimalSeparator(key) && super.onOtherKey(key, hold);
	}
```

**Comment by sspanak** [comment] 2023-06-09 11:46
@mcfrei, have you had any chance to re-test any of the bugs you opened? I did some good improvements based on all the info you provided and I hope everything is fixed, but I can't confirm anything on my phone.

Please, try out tag `v22.0` when you have time and let me know if we can close anything.

**Comment by felipecrs** [comment] 2023-06-09 15:08
@sspanak is there a chance you can add something like:

```diff
# https://github.com/sspanak/tt9/blob/master/.github/workflows/build.yml
[...]
    - name: Build Release APK
      run: ./gradlew build
    - uses: actions/upload-artifact@v3
      with:
        # You may need to adjust this path
        path: "*.apk"
```

To the build workflow? I'm struggling to build the APK myself, this would simplify testing by a lot.

**Comment by sspanak** [comment] 2023-06-10 12:46
@felipecrs, you may want to wait until v22.0 comes out "officially" next week. My previous message was addressed to **mcfrei** who always builds and uses APKs from source. Alternatively, you could try out [beta 21.12 from last week](https://github.com/sspanak/tt9/releases/tag/v1.0-inital).

**Comment by mcfrei** [comment] 2023-06-11 21:57
fixed and working flawlessly in  09e5e1b (v 22.0)

Thank you very much for supporting this niche device!

The long press `+` and long press `;` are also working, everything's as it needs to be.

One small note, not worth opening an issue: I can see the `[--]` statusbar string in Calculator app, but the keys are working, I wonder if the statusbar is even needed in that mode (I assume it is set in TraditionalT9.onStop)

**Closed** 2023-06-11 21:57 UTC
Labels: bug, device hack

**Comment by sspanak** [comment] 2023-06-12 07:43
> One small note, not worth opening an issue: I can see the [--] statusbar string in Calculator app, but the keys are working, I wonder if the statusbar is even needed in that mode (I assume it is set in TraditionalT9.onStop)

There were some issues with the UI not appearing at all or appearing overs some apps when it shouldn't, so I decided to leave showing hiding entirely to the system. It is still not perfect, but at least it doesn't make the phone unusable, so I thought it is good enough and didn't want to touch it anymore. If I have time I may get back to it. It's no big deal.

**Comment by felipecrs** [comment] 2023-06-27 21:09
I updated today from 20.0 to 22.0, and then the issue is back (LG X100S), unfortunately. I had to downgrade to 20.0 again.

Maybe the fix only works for the Kyocera phone, even though the problem symptom is exactly the same.

**Comment by sspanak** [comment] 2023-06-28 07:46
@felipecrs, the problem on Kyocera was that the TT9 was crashing on every key press and retyping the last typed number on restart. Would it be possible for you to check the error logs in Logcat, when you start seeing double numbers?

**Comment by felipecrs** [comment] 2023-06-28 13:54
Sure. Will do that. Thank you!

**Comment by felipecrs** [comment] 2023-07-03 14:10
Here is what I captured... I'm not sure if I did it correctly, but basically I started logcat and reproduced the issue.

[logcat.txt](https://github.com/sspanak/tt9/files/11937687/logcat.txt)

It happened specifically at 11:06:44 onwards.

Something that I noticed when trying to reproduce it is that it is not always happening. It happens most of times, but not always.

**Comment by sspanak** [comment] 2023-07-04 08:01
> Here is what I captured... I'm not sure if I did it correctly, but basically I started logcat and reproduced the issue.

That's right. The thing is there are no longs from TT9 at that time whatsoever, so I can't really tell what happened. What I've noticed, though, is you were using something called "ToneGenerator" at that time. What is this? This doesn't look like a log from the dialer app. Are you having a problem when trying to dial a number or when doing something else?

**Comment by felipecrs** [comment] 2023-07-04 12:21
I was definitely in the stock Dialer app pressing 1, 2, 3, and so on. I can record a video if you want.

I'm not sure what such "ToneGenerator" is.

> The thing is there are no longs from TT9 at that time whatsoever, so I can't really tell what happened.

Do I need to enable some debug logs somehow or install some different APK to have the logs displayed?

**Comment by sspanak** [comment] 2023-07-05 06:43
> Do I need to enable some debug logs somehow or install some different APK to have the logs displayed?

It is not possible to enable the verbose logs from the settings at the moment.

Anyway, let's hold on with that. In #241, we have discussed a completely new implementation of the numeric modes. I am hoping it will solve all undesired side effects once and for all. Let's see how it goes and if you still have problems after it, I suggest you open a new issue specifically for the LG phone, where we can keep discussing the matter.

I can't believe the most difficult part of making an Android keyboard is making it type numbers... :exploding_head:
