### ISSUE TITLE
DPAD-Center on Cat S22 does not accept suggestions

### ISSUE THREAD

**Issue by justbruce** [sspanak/tt9#169] opened 2023-02-01 05:58 UTC
As the title says, on the Cat S22 Flip, pressing the DPAD-Center doesn't accept the suggestions - instead a newline ( \n ) is inserted.

Multiple applications exhibit this behavior - SMS, NotePad Free, FireFox

I mostly use the space feature to accept new words, but as I was browsing code I noticed that DPAD-Center is supposed to accept, too.  I tried it out and it just plain doesn't do that.

 It is possible that this phone doesn't return the proper keycode when DPAD-Center is pressed, but I can't find the app I used to use for intercepting keycodes on the Play Store so it is hard to tell

If this is a quirk unique to this phone then I'll close this and continue using space to accept suggestions. Oh, and I'll volunteer to maintain an errata page on the site

**Comment by sspanak** [comment] 2023-02-01 09:07
It sounds to me like Cat chose to put ENTER key instead of OK key on their phone. Android supports two different keys with similar functions (yes, it is techincally possible to have a keypad with both!) and it seems there is no standard which one is in the center of the DPAD.

Currently, Traditional T9 handles OK, but not ENTER, so this may be the reason the key does not work for you.

In order to get to the bottom of this, could you please use KeyEvent Display app and tell me what it prints when you press DPAD CENTER? You can find it on [Play Store](https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay&hl=en_US&gl=US) and on [APK Pure](https://apkpure.com/keyevent-display/aws.apps.keyeventdisplay).

> If this is a quirk unique to this phone then I'll close this and continue using space to accept suggestions

This is not the intended behavior and it must be fixed. It is probably the same on other phones.

**Comment by justbruce** [comment] 2023-02-02 02:47
KeyUp     :action=1  code=66  repeat=0  meta=0  scanCode=28  flags=8  label='10'  chars='null'  number='0'

**Comment by sspanak** [comment] 2023-02-02 09:04
Yep, code 66 is definitely ENTER, [as per the docs](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_ENTER).

This means both `KeyEvent.KEYCODE_ENTER` and `KeyEvent.KEYCODE_DPAD_CENTER` must be handled the same way in `KeyPadHandler`.

Thanks, justbruce! Stay tuned for version 17.

**Comment by levone1** [comment] 2023-02-03 03:21
> Yep, code 66 is definitely ENTER, [as per the docs](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_ENTER).
> 
> This means both `KeyEvent.KEYCODE_ENTER` and `KeyEvent.KEYCODE_DPAD_CENTER` must be handled the same way in `KeyPadHandler`.
> 
> Thanks, justbruce! Stay tuned for version 17.

Was just going through issues, about to report the same...  I see there was an update today - that wasn't the v.17 you were referring to, was it?  Still the same issue for me, (Schok Flip)...  Thanks

**Comment by sspanak** [comment] 2023-02-03 07:57
> I see there was an update today - that wasn't the v.17 you were referring to, was it?

No, the current version is 16 and this bug is going to be fixed in 17.

**Comment by levone1** [comment] 2023-02-03 18:06
> > I see there was an update today - that wasn't the v.17 you were referring to, was it?
> 
> No, the current version is 16 and this bug is going to be fixed in 17.

Thank you..  Sorry - I could have just checked.  Was in the middle of a few things, and just wanted to ask while I was thinking of it.

**Comment by sspanak** [comment] 2023-02-09 12:54
The bug should be fixed now. But I don't have a phone with this kind of OK key to verify it for real. @levone1, @justbruce, feel free to try out [beta-16.3](https://github.com/sspanak/tt9/releases/tag/beta-16.3) and let me know if something is still missing.

**Comment by levone1** [comment] 2023-02-09 13:46
> The bug should be fixed now. But I don't have a phone with this kind of OK key to verify it for real. @levone1, @justbruce, feel free to try out [beta-16.3](https://github.com/sspanak/tt9/releases/tag/beta-16.3) and let me know if something is still missing.

Yep - perfect.  Thanks...  One little thing to put out there - not a but, and not even an issue with the app; it's probably phone-specific, which is nothing on you - I usually choose not to show on-screen keys, because they don't work with my phone.  Pressing left or right function key does nothing.  The hotkeys work fine, though, so I'm just used to that.  I just had the thought that it might be helpful to have the on-screen keys working.  Maybe there's an apk edit I could try, or a button remap, etc...  I know in the original tt9 app, you could create a button remap file; is that still the case?

Anyway, thanks again.  Great app

**Comment by sspanak** [comment] 2023-02-09 16:39
Left or right will not open the settings screen. 

Indeed, the manual is unclear how to get there, if you have forgotten the hotkey. There is an alternative way, though. Please, see: #177 and if you have more questions, let's continue the discussion there. This issue is about the OK key.

**Comment by justbruce** [comment] 2023-02-10 04:34
> The bug should be fixed now. But I don't have a phone with this kind of OK key to verify it for real. @levone1, @justbruce, feel free to try out [beta-16.3](https://github.com/sspanak/tt9/releases/tag/beta-16.3) and let me know if something is still missing.

DPAD-Center does in fact now accept suggestions, but I get a bonus action of a carriage return or [if i'm using SMS or Signal Private Messenger] the message is sent.

  The "Enter sends" is I'm sure due to settings in each program, but I guess I was hoping that TT9 would trap the "ENTER" KeyEvent.  Maybe make Holding the DPAD-Center emit the Enter key?

**Comment by sspanak** [comment] 2023-02-10 10:48
> DPAD-Center does in fact now accept suggestions, but I get a bonus action of a carriage return or [if i'm using SMS or Signal Private Messenger] the message is sent.

My bad, I have overlooked something. Thanks for pointing it out.

Please, try again with the newly attached file [in the same release](https://github.com/sspanak/tt9/releases/tag/beta-16.3). It will say it is version 16.3 again, but it is different. You can safely install it over the previous one. There will be no data loss.

**Comment by justbruce** [comment] 2023-02-14 06:04
> > DPAD-Center does in fact now accept suggestions, but I get a bonus action of a carriage return or [if i'm using SMS or Signal Private Messenger] the message is sent.
> 
> My bad, I have overlooked something. Thanks for pointing it out.
> 
> ~Please, try again with the newly attached file [in the same release](https://github.com/sspanak/tt9/releases/tag/beta-16.3). It will say it is version 16.3 again, but it is different. You can safely install it over the previous one. There will be no data loss.~
> 
> Please, try again with [beta-16.5](https://github.com/sspanak/tt9/releases/tag/beta-16.5).

I downloaded the version 16.3 and the extra action noted in my previous comment is gone.  The changes introduced seem to have corrected this bug.

I am downloading 16.5 to check for regressions

**Closed** 2023-02-15 11:37 UTC
Labels: bug

**Comment by levone1** [comment] 2023-02-15 13:56
Just a little request... When the word I'm looking for shows up on the suggest list, and then I press '1', it will show som suggestions for contractions, (you'll, you're, etc.) - very helpful, but I wish it would also by default include the most common punctuations, (. , : ; etc).  

I know off-topic, but probably not worth it's own issue...

Thanks

**Comment by sspanak** [comment] 2023-02-16 08:49
> I know off-topic, but probably not worth it's own issue...

@levone1, let's avoid off-topic. My main language is not English, so I can not say it is something that bothers me much, but if it inconvenient from a native speaker's perspective, then it is worth a new issue.
