### ISSUE TITLE
Keyboard has stopped [on Sonim XP3]

### ISSUE THREAD

**Issue by alexknop** [sspanak/tt9#207] opened 2023-03-07 14:38 UTC
My Keyboard is crashing on two scenarios:

1. When opening the Clock app and going to add a new alarm, selecting a time for the alarm typically prompts the 123 keyboard. When I open the "set time" menu, I am seeing "Traditional T9 has stopped". I am wondering if it can't really handle calls for the 123 keyboard or if since I last used the T9/En keyboard for texting, is it trying to default to that when I go to set a time?

2. My Sonim allows me to close the clamshell of the phone on whatever screen I am on and when I open the clamshell it will be on the same screen. When I close the clamshell with the Traditional T9 keyboard open (say in the middle of composing a message), opening the clamshell will also say "Traditional T9 has stopped" It seems the app cannot "re-open". It's possible the activity is getting destroyed when I close the clamshell and certain states are not being saved for when the activity is re-opened. I wonder if this would act the same for letting your screen timeout for a significant amount of time.

**Comment by sspanak** [comment] 2023-03-07 15:51
TT9 does support numeric mode. As a matter of fact, it's a very simple piece of code that just passes through the numbers to Android, so I have no idea what could be causing the crash. Your phone seems to have quite a customized version of Android, so it must be something very specific again.

It would be very difficult for me to determine what is wrong in both cases, since I don't have the phone in my hands. If you know how to switch your phone to developer mode and read the error(s) in Logcat at the moment of the crash, I could examine them and try to think of something. Otherwise, I have no clue... sorry.

_P.S. If someone else is reading this, the phone in question is Sonim XP3._

**Comment by alexknop** [comment] 2023-03-07 16:03
[logs.txt](https://github.com/sspanak/tt9/files/10911434/logs.txt)
Here is what happens when I close/open the clamshell

**Comment by justbruce** [comment] 2023-03-08 03:43
Looks like we are leaving a parent instance open when we shouldn't.

Haven't traced back into code but the giveaway in the logs is 

"AndroidRuntime: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first."

**Comment by sspanak** [comment] 2023-03-08 07:59
Yes, it is a good start. Thanks!

**Comment by sspanak** [comment] 2023-03-21 12:07
@alexknop, could you please try if [this .apk](https://github.com/sspanak/tt9/releases/download/testing/tt9-v19.2+double-action-ok.apk) fixes the crash when you close and open the phone while typing?

Also, I didn't get, do you see the same error when you try to set an alarm, or is it a different one?

**Comment by alexknop** [comment] 2023-03-23 03:21
> @alexknop, could you please try if [this .apk](https://github.com/sspanak/tt9/releases/download/testing/tt9-v19.2+double-action-ok.apk) fixes the crash when you close and open the phone while typing?
> 
> Also, I didn't get, do you see the same error when you try to set an alarm, or is it a different one?

Yes, that fixed the issue. Excellent work sir. I will go back to using this as my primary keyboard and let you know if I get an error related to my alarm app and try to also capture that in logcat. Hopefully it was related and now fixed. Cheers

**Comment by alexknop** [comment] 2023-03-23 03:42
> @alexknop, could you please try if [this .apk](https://github.com/sspanak/tt9/releases/download/testing/tt9-v19.2+double-action-ok.apk) fixes the crash when you close and open the phone while typing?
> 
> Also, I didn't get, do you see the same error when you try to set an alarm, or is it a different one?

Looks like the issue still exists.
[errorlogs.txt](https://github.com/sspanak/tt9/files/11046670/errorlogs.txt)

```
03-22 23:40:05.376  3514  3514 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
03-22 23:40:05.384  1741  1741 D AndroidRuntime: Shutting down VM
03-22 23:40:05.386  1741  1741 E AndroidRuntime: FATAL EXCEPTION: main
03-22 23:40:05.386  1741  1741 E AndroidRuntime: Process: io.github.sspanak.tt9, PID: 1741
03-22 23:40:05.386  1741  1741 E AndroidRuntime: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:4937)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4768)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4740)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService.setInputView(InputMethodService.java:1417)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:1264)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService.showWindowInner(InputMethodService.java:1656)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:1624)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at io.github.sspanak.tt9.ime.TraditionalT9.L(Unknown Source:55)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at io.github.sspanak.tt9.ime.TraditionalT9.s(Unknown Source:38)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at io.github.sspanak.tt9.ime.b.onStartInput(Unknown Source:6)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at io.github.sspanak.tt9.ime.TraditionalT9.onStartInput(Unknown Source:0)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:1823)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService.resetStateForNewConfiguration(InputMethodService.java:935)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService.onConfigurationChanged(InputMethodService.java:923)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4878)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5064)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1713)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6539)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:476)
03-22 23:40:05.386  1741  1741 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-22 23:40:05.386  3514  3514 W IInputConnectionWrapper: setComposingText on inactive InputConnection
```

**Comment by sspanak** [comment] 2023-03-24 09:10
This probably happens in `TraditionalT9.initUi()` inside this:
```
if (!isInputViewShown()) {
	showWindow(true);
}
```

Both `showStatusIcon()` and `showWindow()` are occasionally causing warnings on my phone, but no crashing. I don't know why is that and if there are additional problems on the Sonim, though. Anyway, I do intend to deal with both of them soon.

**Comment by sspanak** [comment] 2023-04-20 07:29
So I've managed to reproduce the "The specified child already has a parent" error on my phone when the screen goes off, and fixed it. However, I am not sure if it is the same as closing the Sonim. @alexknop, could you please try out the [latest beta release](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v20.1.apk) and let me know if the problem is resolved?

**Comment by alexknop** [comment] 2023-04-27 15:01
> So I've managed to reproduce the "The specified child already has a parent" error on my phone when the screen goes off, and fixed it. However, I am not sure if it is the same as closing the Sonim. @alexknop, could you please try out the [latest beta release](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v20.1.apk) and let me know if the problem is resolved?

Yeah that fixed it. Really nice job on the update by the way, I like all of the new features such as the app icon and initial setup menu. It's working very well.

**Comment by sspanak** [comment] 2023-04-28 05:19
Excellent! I am closing the issue then.

> Really nice job on the update by the way, I like all of the new features such as the app icon and initial setup menu. It's working very well.

Thanks! This release (v21.0, that is not out yet) is really a big one and includes many, many improvements.

**Closed by sspanak** 2023-04-28 05:19 UTC
Labels: bug, device hack
