### ISSUE TITLE
v27 Bugs on Sonim XP3plus

### ISSUE THREAD

**Issue by theancientways** [sspanak/tt9#435] opened 2024-02-16 05:04 UTC
Downloaded v27 today and two bugs I'm noticing right off the bat are: 

1. The 4 key is stuck on defaulting to "H", whereas v26 immediately learned to default to "I", which is obviously typed much more frequently. 
2. When I opened a text message up in v26, the first key I pressed would type something. In v27 the first keypress "activates" TT9, and the second key press then types something. 

There seems to still be an issue with missed keypresses but I need to spend more time with it to verify. If there are new settings that are causing these issues that I don't know about my bad, but please let me know if there are. 

Edit: I'm also noticing when I add a new word to the dictionary, before the popup would happen in whatever text window I was in, now the popup takes me to the app settings, and then after pressing ok I have to navigate all the way back to the text window I was in.

**Comment by sspanak** [comment] 2024-02-19 09:38
1. I see. There is a problem with uppercase words in general, not just "I". I'll fix it in the next version.
2. This is intentional. By default, Android does not activate the keyboard until you touch a text or number field. This is how many apps are designed, not taking into account there are non-touchscreen phones. 

Here is the longer explanation of 2, if you are curious why is that. In the beginning, TT9 used to always automatically activate itself, but there were many reports it wouldn't deactivate when one finished typing. This is because Android doesn't know how to handle the case when the keyboard activates itself, instead of the current application activating it. The last two examples are #364 and #367, but the same happens in other applications and on other phones, too. And now, the control is entirely in your hands. If the app decides not to activate TT9 on startup, you can do so using OK, or by touching the screen, as per the Android standard.

I realize this may cause inconvenience, but it is the lesser of two evils.

Also, after discussing the same in #429, I realized all this is a bit unclear. I'll add the explanation in the manual to avoid the confusion to some extent.

**Comment by theancientways** [comment] 2024-02-22 22:01
The lagging issue does seem better. The "pressing once to activate TT9" can be easily gotten used to, and sounds like capitalization will be fixed. Just bought you 5 beers man, thanks for the great work.

**Comment by sspanak** [comment] 2024-02-23 13:51
I have fixed small bugs, somewhat related to what you reported. The only thing I could not reproduce was the Add Word window navigating to some other screen. However, I have changed the way it works completely, so the problem might have just went away. Let's wait for v28.0 a couple more days and see how it works. If you are still experiencing any of the above, please report back.

> Just bought you 5 beers man, thanks for the great work.

Much appreciated!

**Comment by sspanak** [comment] 2024-03-01 09:26
@theancientways, v28.0 is out. Please, install and let me know if any of the issues still persists. I think I was able to fix everything, besides the Add Words thing, which I was not able to reproduce.

**Comment by theancientways** [comment] 2024-03-10 02:47
@sspanak I don't know what you did in v28.0 but you fixed the lag issues on the Sonim XP3plus. I also see you fixed the "add word" and upper case word issues. Kudos!! Donating again to thank you.

**Comment by sspanak** [comment] 2024-03-10 10:17
Excellent! And thank you for the donation again.

Since there is nothing left to do, I am closing this.

**Closed by sspanak** 2024-03-10 10:17 UTC
Labels: bug
