### ISSUE TITLE
In some cases changing candidate word selection (without accepting selection) types two words into text field.

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#286] opened 2023-06-09 16:17 UTC
I discovered this when I tried to change the title and author in a document I wanted to send to my Kindle using the SendToKindle function in the Kindle app. While I selected the right word from the candidates, the text field was filled with a lot of duplicate words.

**Comment by qascot** [comment] 2023-06-09 16:23
I tested with another keyboard, based on Clam's old version and this issue did not occur. So I can say that the bug is not in the Kindle app.

**Comment by sspanak** [comment] 2023-06-10 06:26
I am not familiar with this application and I saw there several ones that go by the same name. Could you please provide a link to it, so I know which one to test?

**Comment by qascot** [comment] 2023-06-10 16:45
I found this version somewhere on the internet and tried to use it on my F21pro. I tried to change this version a bit for my convenience, but I couldn't solve some problems. Your keyboard has become a wonderful discovery for me. But some issues ( #202, #252, #286) are not present in the old one. Thats why I opened those issues, trying to help you to make your keyboard better. 
[SoftMan TraditionalT9.zip](https://github.com/sspanak/tt9/files/11712870/SoftMan.TraditionalT9.zip)

**Comment by qascot** [comment] 2023-06-10 17:53
I meant Amazon Kindle. https://play.google.com/store/apps/details?id=com.amazon.kindle

**Comment by sspanak** [comment] 2023-06-30 08:16
I installed the app, but I can't find the file manager. Where is it supposed to be? Do I need to have bought at least one book (I never had) or is it possible to test with a random document on the phone?

**Comment by qascot** [comment] 2023-07-12 16:04
You could use any file manager app to share book to Kindle. On my DuoQin F21pro I have built-in Files app. You don't need to buy ebook. Use .doc or .pdf instead of ebook file. Open Files app (or any other you used to use), select a random document file in file manager (.doc, .pdf or .epub), choose share from context menu, choose Amazon Kindle and try to change title and author fields. You need to be logged in Amazon account in Kindle app.

**Comment by sspanak** [comment] 2023-07-24 12:17
I've managed to reproduce it. Thanks for the hints!

Note to self: What causes double words is actually scrolling through the suggestions list. Selecting the previous/next word does not set the composing text, but instead types the word directly.

**Comment by qascot** [comment] 2023-07-27 08:41
This bug is only in the mode Predictive. Mode ABC works without issue. Even if scrolling the suggestions list by DPAD not by multi press on number. Maybe this helps.

**Comment by sspanak** [comment] 2023-07-27 08:49
Thanks for the clue! It makes the bug even stranger, though. Never mind, I am not actively working on this, I am just collecting as much info as possible, so that I have a starting point when I get to it.

**Comment by sspanak** [comment] 2023-08-22 15:41
Hey, @qascot, I have managed to get to the bottom of this. It turned out the problem is in the Kindle app, not in TT9. Those two text fields are calling `InputMethodService.onUpdateSelection()` with incorrect arguments, causing weird side effects.

Now, normally, I wouldn't have been fond of "fixing" problems of other apps, but I've spent so much time investigating and since I am willing to implement one more application hack (#244), I've decided to fix it after all. 

Unfortunately, this comes with a performance penalty. While, the problematic text fields are focused, scrolling the suggestions and using Backspace would lag a bit. There is simply no other way, I had to do some heavy text processing. All other text fields, including in the Kindle app, will not be affected and will work smoothly.

Please, try out [v25.6](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v25.6.apk) and let me know if it feels OK.

P.S. Sometimes, I have the feeling I am using way too many words to say very simple things... :smile:

**Comment by qascot** [comment] 2023-08-23 06:43
Hi! I've tested this version a bit. Thank you for your efforts! Kindle text fields seems to work well now. The performance is sufficient enough. But I've found a problem in other cases - an unexpected accepting a letter in the mode ABC. This problem appears in all apps I tested, and isn't present in the version 25. When pressing on number sequentally and fast, sometimes only first letter being printed twice or thrice in the text field. This happens quite often, but I couldn't find any specific conditions to get this bug. 

P.S. Can I see the code changes you’ve made? Perhaps I could implement it in my test version where I’m trying to solve the issues I found and make the user experience suitable for me. Because I think you won’t have enough time to work on such a specific issue. Unfortunately I am not a programmer so I stuck on v.17 with all my changes and can’t help you developing your undoubtedly wonderful application.

P.P.S. The simpler a thing seems, the more words you need to explain exactly what do you mean.

**Comment by sspanak** [comment] 2023-08-23 12:45
> I've found a problem in other cases - an unexpected accepting a letter in the mode ABC.

Yep, I found that several hours later, but it was too late. Anyway, I fixed in [version 25.8](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v25.8.apk). I even came up with a better way of doing it that does not slow down scrolling.

>  Can I see the code changes you’ve made?

Of course, you can see everything on Github. The commit is [here](https://github.com/sspanak/tt9/pull/358/commits/39d4d7d85642ffc72c8d14c03b642584d5fcfc8b), but have in mind it also fixes several more small things, and it prepares the code base for the next commit, so in the context of the Kindle bug, some of the changes are irrelevant.

> Unfortunately I am not a programmer so I stuck on v.17 with all my changes and can’t help you developing your undoubtedly wonderful application.

I am changing the code base a lot, all the time, so I get it is difficult to stay in sync. But Tradtional T9 has evolved a lot since version 17 and I definitely recommend upgrading. Typing is much easier (well, it depends on the language), many, many bugs were fixed and some cool new features are now on. I am curious what critical features have you added, that are worth holding back the upgrade?

**Closed** 2023-08-29 08:49 UTC
Labels: bug
