### ISSUE TITLE
Can't add word to dictionary

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#322] opened 2023-07-28 12:20 UTC
I keep trying to add words to the dictionary but it does not save them

https://github.com/sspanak/tt9/assets/14912461/dbfcd699-dde4-4ee8-9f20-97c6f977de67

I'm either doing something wrong or there is a bug on it. 

(also... is the " **+** " button destined for adding words??? Because I could not make it work until now)

**Comment by sspanak** [comment] 2023-07-29 09:28
Yes, you are pressing the right buttons and indeed, it looks like it does not work on your phone. I am not sure what could be wrong, because no error message appears either.

I have some questions:
1. What is the exact make and model of your phone? 
2. What other languages do you have enabled and have you loaded their dictionaries? 
3. Have you tried adding new words while in another app? 
4. Have you tried clearing and reloading all words (Settings -> Languages -> Clear All, then re-load)? Perhaps the database has become corrupted for some reason?

**Comment by maverick74** [comment] 2023-08-01 14:21
1.Xiaomi Redmi 5
2.Portuguese and English
3.Not sure what you mean so ill answer both: in any other app I cannot add words. Using touchpal I could add any words!
4. Will try and ill report in a few moments

**Comment by maverick74** [comment] 2023-08-01 14:39
4.Now that s funny because, after the steps you recommended, it no longer reports wrong or non-existent words!!!

**Comment by sspanak** [comment] 2023-08-01 14:59
So you are saying it's working fine now?

**Comment by maverick74** [comment] 2023-08-01 16:16
> So you are saying it's working fine now?

No! Quite the opposite!

It stopped identifying wrong/unknown words and, as such, Im not getting the option to "add a new word!"

**Comment by sspanak** [comment] 2023-08-02 07:20
This sounds really strange. It has never happened to me and no one else has ever complained they can't add words, so it must be a problem specific only to your phone.

I'll double check the code for adding new words, but I can't think of anything wrong with it. For the moment, I have no idea how to fix it. Sorry!

If anyone with a Redmi 5 is willing to debug, check `DictionaryDb.insertWord()` function.

**Comment by maverick74** [comment] 2023-08-02 11:33
OK... in the meanwhile it seems to have started again to identify wrong/unknown words.
Maybe it was indexing or loading something... or needed a phone restart... i don't know...
but it seems to be working again!!!

Adding new words, however, is **not possible**!

**Comment by maverick74** [comment] 2023-08-02 11:53
OK... Here's some clues about it:

**I was able to put the + button working**! To do that, i've reviewed the app permissions settings and "allowed" everything.
I believe it was the pop-up windows permissions (that was off) that did the trick, because before, when i pressed the + button, i did not get any dialog asking me the word i wanted to add

So, i can now add words to the dictionary for the first time :)

_**However**_, **the process shown on the video** - where i type a word that is not recognized, it is identified as a wrong word and then i ask to add it to the dictionary - still **does not work** even with this permissions set!

**Comment by sspanak** [comment] 2023-08-03 07:40
Hang on, hang on...

1. By a word being identified as wrong, do you mean that it is underlined in red? If yes, just ignore it. TT9 does not analyze the text like this, it's Android doing it.

2. Are you trying to add words using this "popup":
![Screenshot_20230803_102250](https://github.com/sspanak/tt9/assets/27846105/5f1e372f-1696-4013-a135-573455ea01fb)
Again, this is not part of TT9. This one allows you to add or use words from the system dictionary which is used by Gboard (the Google Keyboard) or others based on it. This is built in Android for convenience, assuming people would only use QWERTY keyboards.

Now, technically, TT9 has access to that dictionary, but it is of no use, because it does not contain information about the digit combinations. I was considering of using it at the beginning, but it is not possible, unfortunately.

The correct way of adding words is:
1. Compose the the new word in some application where you can type. 
2. Make sure it is in the correct text case, because it is going to be stored the way you see it.
3. Move the text cursor next to or inside the word.
4. Hit the "+" button.
5. Press "OK" to confirm and save.

And that's it, there are no two ways of adding words. Unless an error message appears, the word should be in the dictionary now.

However, from what I see in the video, this did not work initially. I assume it was because of the missing permissions. Speaking of them, usually, you don't need to grant anything extra, but Android experience may vary a lot from phone to phone and Xiaomi may have added some non-standard permission on yours. I have no idea about that.

Now, having said all this, do you still have a problem?

**Comment by maverick74** [comment] 2023-08-03 09:26
Oh! I see!!!

I was using it wrongly then!!!

So, if this is the case, you can close this issue because all this related to it are solved!!!

Still, if its possible, I believe it would be good to disable the "_Android thing_." because it causes lots of confusion - as we've seen already

**Comment by sspanak** [comment] 2023-08-03 12:06
> Still, if its possible, I believe it would be good to disable the "Android thing" because it causes lots of confusion - as we've seen already

Sorry, I have no control over this.

Anyway, since the problem is solved, I am closing this.

**Closed by sspanak** 2023-08-03 12:06 UTC
Labels: question
